### ISSUE TITLE
插件install方法第二个参数options无法生效

### ISSUE THREAD

**Issue by diablogatox** [zhaohaodang/vue-see#1]
大神好，鄙人想在安装插件的时候传入photoswipe的参数来改变photoswipe的一些行为，比如修改弹框背景透明度，请问可以实现吗

**Comment by diablogatox** [comment]
![2017-07-19 17-50-38](https://user-images.githubusercontent.com/7379371/28361257-ceaa5838-6caa-11e7-9650-c031f3acd010.png)

**Comment by zhaohaodang** [comment]
vue-see新的1.2.0版本支持传参 ，[查看](https://github.com/zhaohaodang/vue-see/releases/tag/1.2.0)

**Comment by suizhiwen** [comment]
请问 安装插件后打包  Uncaught SyntaxError: Unexpected token import  报import错误是怎么回事

**Comment by suizhiwen** [comment]
import PhotoSwipe from './photoswipe/photoswipe.min.js'
	import PhotoSwipeUI_Default from './photoswipe/default-skin/photoswipe-ui-default.min.js'
	import './photoswipe/photoswipe.min.css'
	import './photoswipe/default-skin/default-skin.css'
报import错的位置是这几个    我看了下文件 路径应该是没错  麻烦帮忙解答一下

**Comment by zhaohaodang** [comment]
使用Babel

2017-09-01 16:45 GMT+08:00 suizhiwen <notifications@github.com>:

**Comment by zhaohaodang** [comment]
你可能没有使用Babel

**Comment by suizhiwen** [comment]
{
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      }
webpack默认有这个配置  编译是不包括 node_modules 里面的东西，我如果把    exclude: /node_modules/ 给去掉的话 ，又报一个莫名其妙的错误，可是安装其他的包没有出过这个问题，最近做个项目很需要朋友你这款插件，261630116，这是我Q号，朋友能拔刀相助吗

**Comment by suizhiwen** [comment]
babel是用了的    只是貌似默认不编译 node_modules 的东西，为什么其他插件没有这个问题呢，唉

**Comment by zhaohaodang** [comment]
改成
```javascript
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [resolve('src'), resolve('test')]
}
```
试一试
