### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Frank-MJ** [zhaohaodang/vue-see#10]
![image](https://user-images.githubusercontent.com/16225885/37333558-9b02467c-26e4-11e8-93c9-59ffac96f18f.png)

**Comment by zhaohaodang** [comment]
https://www.google.com.hk/search?q=You+are+using+the+runtime-only+build+of+Vue+where+the+template+compiler+is+not+available.+Either+pre&oq=You+are+using+the+runtime-only+build+of+Vue+where+the+template+compiler+is+not+available.+Either+pre&aqs=chrome..69i57j69i60j69i64.238j0j3&sourceid=chrome&ie=UTF-8
