### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by caolonggang** [zhaohaodang/vue-see#11]
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

加了resolve: {
        alias: {
            ‘vue$‘: ‘vue/dist/vue.js‘
        }
    }
还是报错

**Comment by zhaohaodang** [comment]
https://www.google.com.hk/search?q=You+are+using+the+runtime-only+build+of+Vue+where+the+template+compiler+is+not+available.+Either+pre&oq=You+are+using+the+runtime-only+build+of+Vue+where+the+template+compiler+is+not+available.+Either+pre&aqs=chrome..69i57j69i60j69i64.238j0j3&sourceid=chrome&ie=UTF-8
