### ISSUE TITLE
老哥，这个url为什么跑到上面去啊？详见下，不知道是不是for循环的问题

### ISSUE THREAD

**Issue by jonnzer** [zhaohaodang/vue-see#2]
![image](https://user-images.githubusercontent.com/21023707/31378346-8b60c7e6-addd-11e7-9490-d35affae5c27.png)

**Comment by zhaohaodang** [comment]
贴完整代码

**Comment by zhaohaodang** [comment]
```javascript
<see-item v-for="(item,index) in imgList" :key="index"  :u="item.u"></see-item>
```
上面写法是无效的，你不应该显式地为`see-item`组件传递`u`参数，为了简化代码，你应该传递包含`u`属性的`item`对象：
```javascript
<see-item v-for="(item,index) in imgList" :key="index"  :img="item"></see-item>
```

**Comment by jonnzer** [comment]
哥们，感谢啊，你解决了我的问题

**Comment by jonnzer** [comment]
![image](https://user-images.githubusercontent.com/21023707/31420796-4cbbd85c-ae76-11e7-991e-c00c7aa8f86f.png)
老哥，这个样式明明有加载，顶部那三按钮它死活不出来呢，这是啥问题呢
