### ISSUE TITLE
点击图片时报错，然后因为是photoswipe.min.js无法调试

### ISSUE THREAD

**Issue by jonnzer** [zhaohaodang/vue-see#3]
![image](https://user-images.githubusercontent.com/21023707/31699307-d970ce78-b3f4-11e7-8438-c73074a50f59.png)

**Comment by jonnzer** [comment]
因为我访问图片裂图，我在审查元素改变图片url，是不是这个导致呢？它的数据结构和图片没对应起来

**Comment by zhaohaodang** [comment]
看看是不是这个issue #2

**Comment by jonnzer** [comment]
不是呀，我不会再显式的定义U属性了

**Comment by zhaohaodang** [comment]
贴完整的代码

**Comment by jonnzer** [comment]
![image](https://user-images.githubusercontent.com/21023707/31707823-eebf77e0-b41f-11e7-9386-3b238ef722c2.png)

**Comment by zhaohaodang** [comment]
上面images里的键名以键值应该是这种
```javascript
 {
     u: string,
     w: number,
     h: number,
     c: string
 }
```
这个插件不友好的地方就在这，亟待改善
