### ISSUE TITLE
是否可以點擊某一個連結，才開啟隱藏的images呢？

### ISSUE THREAD

**Issue by sharenjoy** [zhaohaodang/vue-see#4]
是否可以點擊某一個連結，才開啟隱藏的圖片呢？而圖片在頁面上始終一直是隱藏的。

**Comment by zhaohaodang** [comment]
参考 [http://photoswipe.com/documentation/getting-started.html](http://photoswipe.com/documentation/getting-started.html)

**Comment by sharenjoy** [comment]
多謝
